INFOS:
  idBal: 1862
  nom: Balise1
  lieu: Accueil
  default_message: 1
  autovolume: false
  volume: 86
  plages_horaire: false
DEFAULT:
  volume: 72
  autovolume: false
  second_message: true
  second_message_switch: true
  switch_pin: 4
ANNONCES:
- id_annonce: 0
  nom: salut
  type: TEXTE
  filename: Balise1-0.wav
  contenu: salut
  lang: fr
  duree: 0
- id_annonce: 1
  nom: g
  type: AUDIO
  filename: Balise1-1.wav
  contenu: ''
  lang: ''
  duree: 2
- id_annonce: 2
  nom: fgg
  type: AUDIO
  filename: aaaah.m4a7751902633298844232.tmp
  contenu: ''
  lang: ''
  duree: 2
- id_annonce: 0
  nom: jdjd
  type: AUDIO
  filename: Balise1-0.wav
  contenu: ''
  lang: ''
  duree: 1
- id_annonce: 0
  nom: jdkd
  type: AUDIO
  filename: Balise1-0.wav
  contenu: ''
  lang: ''
  duree: 1
- id_annonce: 0
  nom: salut
  type: TEXTE
  filename: Balise1-0.wav
  contenu: salut
  lang: en
  duree: 0
- id_annonce: 1
  nom: baaba
  type: AUDIO
  filename: Balise1-1.wav
  contenu: ''
  lang: ''
  duree: 2
- id_annonce: 2
  nom: Bonjour
  type: TEXTE
  filename: Balise1-2.wav
  contenu: Bonjour et bienvenue  l'accueil des petits debrouillards, nous sommes ouverts
    de 9h a 17h et c'est super sympa
  lang: fr
  duree: 0
- id_annonce: 0
  nom: salut
  type: TEXTE
  filename: Balise1-0.wav
  contenu: salut
  lang: fr
  duree: 0
- id_annonce: 1
  nom: hh
  type: AUDIO
  filename: Balise1-1.wav
  contenu: ''
  lang: ''
  duree: 1
- id_annonce: 0
  nom: salut
  type: TEXTE
  filename: Balise1-0.wav
  contenu: samut
  lang: fr
  duree: 940
- id_annonce: 0
  nom: Salut
  type: AUDIO
  filename: Balise1-0.wav
  contenu: Salut
  lang: fr
  duree: 0
- id_annonce: 1
  nom: Test
  type: AUDIO
  filename: Balise1-1.wav
  contenu: "Bonjour et bienvenue au McDonald's de Clermont Ferrand, nous pouvons vous\
    \ h\xE9berger si vous le souhaitez car nous sommes des personnes fort sympathique"
  lang: fr
  duree: 0
OPTIONS:
  multiple_announces: true
  internet_access: true
  tts: false
