INFOS:
  idBal: 1862
  nom: UNADEV
  lieu: "Entr\xE9e"
  default_message: 0
  autovolume: true
  volume: 100
  timeslots: true
DEFAULT:
  volume: 72
  autovolume: false
  second_message: true
  second_message_switch: true
  switch_pin: 4
ANNONCES:
  - id_annonce: 0
    nom: Test
    type: TEXTE
    filename: media/examples/bip.wav
    contenu: Bip
    lang: fr
    duree: 1
OPTIONS:
  multiple_announces: true
  internet_access: true
  tts: false
TIME_SLOTS: []
